- hosts: all
  tasks:

    - block:
      # Allows you to SSH in via SSH key, instead of password auth, pulling from your GitHub Public key
      - name: Ensure SSH Key is authorized
        authorized_key:
          user: pi
          state: present
          key: https://github.com/yehoshuadimarsky.keys

      # Update system-level dependencies
      - name: update and upgrade apt packages
        become: true
        apt:
          upgrade: dist
          update_cache: true

      # Ensure timestamps are in my local timezone
      - name: set timezone
        become: true
        community.general.timezone:
          name: America/New_York
      
      # Install and enable NTP to ensure the clock remains accurate
      - name: install ntp
        become: true
        apt:
          name: ntp
          state: present
      - name: enable ntp
        service:
          name: ntp
          state: started
          enabled: true
      tags: system

    - block:
      # Prevents SSH brute force attacks
      - name: install fail2ban
        become: true
        apt:
          name: fail2ban
          state: present

      # Installs firewall
      - name: install ufw
        become: true
        apt:
          name: ufw
          state: present
        register: install_ufw
      
      # Reboot, otherwise issues with ufw
      # https://raspberrypi.stackexchange.com/a/121762
      # https://www.middlewareinventory.com/blog/ansible_wait_for_reboot_to_complete/
      - name: Reboot the server
        become: true
        become_user: root
        shell: "sleep 5 && reboot"
        async: 1
        poll: 0
        when: install_ufw.changed
        register: reboot_after_install_ufw
    
      - name: Wait for the reboot and reconnect 
        wait_for:
          port: 22
          host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
          search_regex: OpenSSH
          delay: 10
          timeout: 60
        connection: local
        when: reboot_after_install_ufw is not skipped

      # Rate limits SSH attempts
      - name: limit ssh
        become: true
        community.general.ufw:
          rule: limit
          port: ssh
          proto: tcp

      # Firewall rules
      - name: Allow all access to SSH, DNS, and WWW
        become: true
        community.general.ufw:
          rule: allow
          name: '{{ item }}'
        loop:
          - SSH
          - DNS
          - WWW
          - WWW Secure
      - name: ufw tcp rules for DHCP + adguard
        become: true
        community.general.ufw:
          rule: allow
          port: '{{ item | int }}'
          proto: tcp
        loop: 
          - 67
          - 3000
      - name: ufw udp rules for DHCP
        become: true
        community.general.ufw:
          rule: allow
          port: '{{ item | int }}'
          proto: udp
        loop: 
          - 67
          - 68
      - name: enable ufw and default to deny
        become: true
        ufw:
          state: enabled
          default: deny
      tags: security

    # Tailscale
    # https://tailscale.com/kb/1103/exit-nodes/#step-1-advertise-a-device-as-an-exit-node
    # Set ip forwarding on in /proc and in the sysctl file and reload if necessary
    - block:
      - ansible.posix.sysctl:
          name: '{{ item }}'
          value: '1'
          sysctl_set: yes
          state: present
          reload: yes
        loop:
          - net.ipv4.ip_forward
          - net.ipv6.conf.all.forwarding
        become: true

      # https://github.com/artis3n/ansible-role-tailscale
      - name: Configure Tailscale
        include_role:
          name: artis3n.tailscale
        vars:
          tailscale_args: "--advertise-exit-node"
          tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
      tags: tailscale
